### ISSUE TITLE
README Filter test code

### ISSUE THREAD

**Issue by RichardWigley** [piotrmurach/tty-table#10]
When I used the example code, using tty version 0.4.0, and adding: `require 'tty'`.

### 3.6 Filter
```
table.render do |renderer|
  renderer.filter = proc do |val, row_index, col_index|
    col_index % 2 == 1 ? TTY.color.set(val, :red, :on_green) : val
  end
end
```

 I was getting it raising an error.

` undefined method 'color' for TTY:Module (NoMethodError)`

Is this code correct? I have been using a work which gets me going:

` col_index % 2 == 1 ? Pastel.new.on_green(val) : val`

**Comment by piotrmurach** [comment]
Hi Richard,
Thanks for using the library and spotting the issue, I've updated the docs. If possible I would recommend using `tty-table` as standalone gem provided you don't need all the dependencies that come with `tty`.
