### ISSUE TITLE
Rotated table missing line separator

### ISSUE THREAD

**Issue by epinault** [piotrmurach/tty-table#12]
When resize is set to false and the table rotate, how do I get a line between each row ?

I am trying this 

            table.render do |renderer|
              renderer.border.separator = :each_row
            end

            puts table.render(:unicode)

but not working :(

**Comment by epinault** [comment]
Doc might be incorrect

this works
 table.render do |renderer|
          renderer.border :separator => :each_row
        end

**Comment by piotrmurach** [comment]
Thanks for using the library. This looks like a bug to me. There are already open issues related to separating records, it may be worth reviewing them. I'm currently too busy to get this sorted. I'm planning to work on `tty-table` in near future. I'm always happy to review any PRs and merge.

**Comment by epinault** [comment]
closing as I don t use Ruby anymore. Maybe someone else will figure this out
