### ISSUE TITLE
border.separator = :each_row

### ISSUE THREAD

**Issue by MadBomber** [piotrmurach/tty-table#18]
This option as documented in the README does not work.  Here is my IRB session:

```
>> require 'tty-table' #=> true
>> table = TTY::Table.new ['header1', 'header2'], [['a1', 'a2'], ['b1', 'b2']]
=> #<TTY::Table header=#<TTY::Table::Header fields=["header1", "header2"]> rows=[#<TTY::Table::Row fields=["a1", "a2"]>, #<TTY::Table::Row fields=["b1", "b2"]>] orientation=#<TTY::Table::Orientation::Horizontal:0x00007f819b8be740 @name=:horizontal> original_rows=nil original_columns=nil>
>> puts table.render(:ascii) do |renderer|
 >       renderer.border.separator = :each_row
|    end #=> nil
+-------+-------+
|header1|header2|
+-------+-------+
|a1     |a2     |
|b1     |b2     |
+-------+-------+
```

**Comment by RylanBauermeister** [comment]
The README is wrong, but it works.  You need to pass it:

renderer.border.separator = TTY::Table::Border::EACH_ROW

**Comment by MadBomber** [comment]
I tryed that and got the same result...
```
>> puts table.render(:ascii) do |renderer|
 >       renderer.border.separator = :each_row
|    end  #=> nil
+-------+-------+
|header1|header2|
+-------+-------+
|a1     |a2     |
|b1     |b2     |
+-------+-------+
>> puts table.render(:ascii) do |renderer|
 >       renderer.border.separator = TTY::Table::Border::EACH_ROW
|    end  #=> nil
+-------+-------+
|header1|header2|
+-------+-------+
|a1     |a2     |
|b1     |b2     |
+-------+-------+
```

**Comment by piotrmurach** [comment]
This option works when the renderer class is used as evidenced in [tests](https://github.com/piotrmurach/tty-table/blob/ea613e2e33134b2f7dc4f349986bfe11eae3607a/spec/unit/renderer/unicode/separator_spec.rb). I'm rather busy now preparing to speak at a conference next week. When I'm back I will try to find some time to look at some issues in this gem. Do you have anytime to submit PR that fixes this?

Re `unicode-display_width` which is used by `strings` dependency. I will upgrade soon to remove such strict versioning.

**Comment by RylanBauermeister** [comment]
@MadBomber The render method seems to have some interesting behavior with regards to what it returns--if you store the rendered table into a variable then put it, it works.

@piotrmurach I'm a student with a pretty busy schedule, but I'll see if I can find a little time to address this.  It's certainly good experience for me to hunt things like this down!

```
rendered = table.render(:ascii) do |renderer|
    renderer.border.separator = TTY::Table::Border::EACH_ROW
end
puts rendered
```

**Comment by RylanBauermeister** [comment]
Okay, I've found some weirdness here.  It looks like the issue isn't actually in the function, but in how it is called in conjunction with puts.  The block executes fine as this:

```
puts table.render(:ascii) { |renderer|
    renderer.border.separator = :each_row
}
```
If you run it as a do/end block, it ignores the function aspect and just calls `table.render(:ascii)`.  This feels more like a problem with ruby's base puts function than with TTY-Table to me, but is certainly worth noting.

**Comment by piotrmurach** [comment]
@RylanBauermeister good find! I wasn't aware of this behaviour.

@MadBomber I've released new `strings` version which should fix the issue with `unicode_display-width` compatibilities. You should be able to install the latest version.
