### ISSUE TITLE
undefined method `rindex' for nil:NilClass when using resize: true

### ISSUE THREAD

**Issue by chqr** [piotrmurach/tty-table#20]
Hello! Thanks for creating this gem, it's been very useful for our team.

We are experiencing a bug where table resize raises an exception. The bug only occurs when terminal size is small enough that table resize is required:

    $ stty size
    21 81
    $ ruby /tmp/test2.rb 
    /usr/local/rvm/gems/ruby-2.3.6/gems/strings-0.1.1/lib/strings/truncate.rb:59:in `truncate': undefined method `rindex' for nil:NilClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.6/gems/strings-0.1.1/lib/strings.rb:98:in `truncate'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operation/truncation.rb:38:in `call'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:59:in `block (4 levels) in apply_to'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:58:in `each'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:58:in `block (3 levels) in apply_to'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:57:in `each'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:57:in `block (2 levels) in apply_to'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:55:in `each'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:55:in `each_with_index'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:55:in `block in apply_to'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:54:in `each'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:54:in `each_with_index'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/operations.rb:54:in `apply_to'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/renderer/basic.rb:203:in `render'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/renderer.rb:77:in `render'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table/renderer.rb:99:in `render_with'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table.rb:452:in `render_with'
        from /usr/local/rvm/gems/ruby-2.3.6/gems/tty-table-0.10.0/lib/tty/table.rb:426:in `render'
        from /tmp/test2.rb:11:in `<main>'

Here is a script to reproduce:

    #!/usr/bin/env ruby
    require 'tty-table'
    table = TTY::Table.new(header: ['my header', 'a', 'b', 'c', 'd'])
    string = 'some long data that must be wrapped'
    table << [string, '', 'data', string, string]
    puts table.render(:unicode, resize: true)

**Comment by snowe2010** [comment]
This is caused due to [these lines](https://github.com/piotrmurach/tty-table/blob/master/lib/tty/table/column_constraint.rb#L143-L145)
producing a width like: `[-24, 10, -30]` or similar. 

I can get the table to actually print by changing `lengths + [renderer.column_widths[col] - ratio]` to `lengths + [renderer.column_widths[col] / ratio]`, but that results in all the columns being the same width (or close to it). I'm not sure what the purpose of this 'ratio' was, so I'm not really sure how to fix this.

**Comment by dmil** [comment]
➕ I'm also having this issue

**Comment by slowbro** [comment]
decided to take a stab at this, brain dumping so I don't forget when I pick it back up tomorrow:

looks like Numeric#clamp (since ruby 2.4) fixes the original issue well:

```
diff --git a/lib/tty/table/column_constraint.rb b/lib/tty/table/column_constraint.rb
index dddacf5..b68178e 100644
--- a/lib/tty/table/column_constraint.rb
+++ b/lib/tty/table/column_constraint.rb
@@ -141,7 +141,8 @@ module TTY
         ratio       = ((natural_width - renderer.width) / column_size.to_f).ceil

         widths = (0...column_size).reduce([]) do |lengths, col|
-          lengths + [renderer.column_widths[col] - ratio]
+          width = (renderer.column_widths[col] - ratio).clamp(minimum_width, renderer.width)
+          lengths << width
         end
         distribute_extra_width(widths)
       end
```

but this exposed a couple issues:

1. the 'trailing' character for Strings.truncate is technically two characters (yay multibyte characters), so making the window size even smaller (63x29 in my case) causes:

```
         5: from /usr/home/kschiesser/code/tty-table/lib/tty/table/operation/truncation.rb:40:in `call'
         4: from /usr/home/kschiesser/.rvm/gems/ruby-2.6.3@laika/gems/strings-0.1.5/lib/strings.rb:99:in `truncate'
         3: from /usr/home/kschiesser/.rvm/gems/ruby-2.6.3@laika/gems/strings-0.1.5/lib/strings/truncate.rb:62:in `truncate'
         2: from /usr/home/kschiesser/.rvm/gems/ruby-2.6.3@laika/gems/strings-0.1.5/lib/strings/truncate.rb:73:in `shorten'
         1: from /usr/home/kschiesser/.rvm/gems/ruby-2.6.3@laika/gems/strings-0.1.5/lib/strings/truncate.rb:102:in `display_width'
/usr/home/kschiesser/.rvm/gems/ruby-2.6.3@laika/gems/strings-ansi-0.1.0/lib/strings/ansi.rb:29:in `sanitize': undefined method `gsub' for nil:NilClass (NoMethodError)
```

2. There is a minimum width that it's viable to even print a table. Looking at Table::ColumnConstraint, I think that `minimum_width * table.columns_size` should be checked, and a friendly "The TTY is too small to display this table" message is in order if the TTY is below that size.

**Comment by slowbro** [comment]
For (1), I lied, the elipsis is a single character (it was just being copy-pasted as a MB character on my system). I fixed the underlying issue for that in strings.

**Comment by piotrmurach** [comment]
@slowbro I do appologies for this codebase, it's been written a long time ago and is in dire need of rewrite. But, as with any open-source, it's hard to find the time. So I really appreciate you looking into this issues despite the code 'cobewebs' 😉

**Comment by slowbro** [comment]
Absolutely! No need to apologize. We use it a lot and I'm having fun :)
