### ISSUE TITLE
anyway to add a separator between arbitrary rows?

### ISSUE THREAD

**Issue by catmando** [piotrmurach/tty-table#22]
would be handy to be able to somehow indicate that there is a separator between two arbitrary rows.

perhaps if a row was not an array but instead the keyword `:separator`  ??

(FYI this is a very nice gem! thanks!)

**Comment by piotrmurach** [comment]
Hi Mitch,

I like the idea, `:separator` sounds good to me. 

Would be really nice if you could implement and submit PR?
