### ISSUE TITLE
table.render outputs nothing when used inside Thor

### ISSUE THREAD

**Issue by codefriar** [piotrmurach/tty-table#38]
### Describe the problem

When using TTY::Table inside a Thor based CLI application the .render method outputs nothing. 

```rb
table = TTY::Table.new(rows: [[1,2], [3,4])
table.render(:unicode)
```

results in
```

```

If you execute 

```rb
puts table.render(:unicode)
```

You see the table as expected. **However** all cell formatting via renderer.filter lamba, as described in the docs is lost. Specifically the Color coding is lost. For instance

```rb
table = TTY::Table.new(rows: [[1,2], [3,4])
say table.render(:unicode) do |render|
  render.filter = ->(val, row_index, col_index) do
    pastel = Pastel.new
    paste.green(val)
  end
end
```

This renders the table, but only in black and white. 

### Expected behaviour
I expected a the cells to have green text.

### Describe your environment

* OS version: alpine 3.12.3 (ruby docker version ruby3-alpine)
* Ruby version: 3.0
* TTY::Table version: 0.12.0

**Comment by piotrmurach** [comment]
Hi Kevin 👋 

Thanks for using `tty-table`. 

The `render` returns table as a string, then it's up to you how you want to display it. I'd appreciate any improvements to the documentation that may help anyone in the future.

Your example will work provided that before printing the result, you assign the returned string like so:

```ruby
table = TTY::Table.new(rows: [[1,2], [3,4])
pastel = Pastel.new
green = pastel.green.detach # creates a proc to make colouring efficient

rendered_table = table.render(:unicode) do |render|
  render.filter = ->(val, row_index, col_index) do
    green[val]
  end
end

say rendered_table
```

Alternatively, when a filter is expressed in a single line block things work fine:

```ruby
say table.render(:unicode) { |r| r.filter = ->(val, ri, ci) { green[val] } }
```

I'm not sure why `say`, which is a wrapper around `puts` call ignores a multiline block. It's one of the mysterious of Ruby and another gotcha that could be added in the documentation. Do you have a minute to submit PR?
