### ISSUE TITLE
`require 'tty-table' failed with undefined method `gunzip' for Gem:Module`

### ISSUE THREAD

**Issue by armahillo** [piotrmurach/tty-table#46]
### Describe the problem

When attempting to use `tty-table`, it outputs this error:

```sh
require 'tty-table' failed with undefined method `gunzip' for Gem:Module
```

I can correct the error by including this at the top of the file, before the Gem is required:

```ruby
module Gem
  module_function
  def gunzip(*args)
    Gem::Util.gunzip(*args)
  end
end
```

### Steps to reproduce the problem

```ruby
# Gemfile
gem 'tty'
```

```ruby
# demo.rb
require 'bundler/setup'
TTY::Table.new(["Test","Data"], [['word', 1]])
```

### Actual behaviour

Prints error message and fails.

### Expected behaviour

I expected it to work.

### Describe your environment

* OS version: MacOS 14.5
* Ruby version: 3.0.6p216
* TTY::Table version: 0.8.0

**Comment by piotrmurach** [comment]
Thanks for giving the `tty-table` a try.

Unfortunately, this error has nothing to do with this gem. It's a problem with Ruby installation on your machine, in particular, the [rubygems](https://github.com/rubygems/rubygems).
